---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bmc-admin-shared
  namespace: metal3
spec:
  encryptedData:
    password: AgCnCDHNJhomW/ec3ModPQNS5pnSJSUF82nTpSPJe0LyUWISc9RqmmNYZW9s0jOzpJNIlNoIlAaToUgDYiIlifTvQejRtstKG2RinhqIM/+iVnYeDLvtbjajBpeivGDcR+dl5h8viLv1/vIOoxwPWLud7+wsiqQZBBcjjBH2O5KV8jcoG1Ps5reNZfwU3RFGbvGI7s7MSK+0B+y9hHLKagNzmTBFyl7tor85lWViGoNgw3jDlDJwYzw7Gp0qTkC2vBI5WFR7KwLPIIipDq8VmyL9/W61o/1gyVNKvAMiqclDF/Jrd62JmMmLdsU5MBbLlG1ml4PgJ0ZpDMvsfwnRXh4UyU4pI0O4H1mPJ0bHa22lPbYC8Ao0hTbc9uKlrANGmKzWFQTvKjIqJnuiywyeQcjkUHoeW6A0bQ+6o5p9AVf/gWr8MVo5KR0S8ZxiZsvnXxsmkPDqiU9yb6LmY4PTJusbdF62caNjhiHF5redjFwmiOwsU1PXuBIJpE5kVVp190ROOUU7uCgAiNTYoymBo9ZgJ7CHpt86DChQJTyzjUtxPRiUbASxwIl7G9Qj+qbffPrqSB3LLEXs09RKkjTJsWsxSxEH5u9tM9Il4s/eFjMsveE07nRfR4ZxEikDT91yAbcVSFNJx4j7q/seN93xPffYbQ0LLTa6AHKVnMriBuAmQZRZcfIwZzwh3WlCx+2TJNREbDXUMQ==
    username: AgCJTujG+VFRfwHpOhEKe/zc7WbWHSi0zoK6YsNMKwzkNnPoqUhbJ/DbAM6NFZ6UEFuCVMayvxnJhW9tJGwuEje1cRmvzqvHAMorTSTWNY2AlsVd1uecuk5dfCwkv9uFfIcRxRymTSgGlvGZbX7n++iBR0jHVlZLCrY92MuoPBoYH/UEj7E7u+GGdpJhg9ZbN5wsKBPlbwreSHBUWH2v22njpRnSA7D7HSwe96qbOYba+GE4lGf8UIgB2CxfLYVsoXYacPMD8pcm+Kvy69YGCWWYMWTV4pdDpAo6sc6TEJpGOVbxFOi8ItyZl6vuN79mE1Oypt0INorGyLYvjzxq8TK5+t2eZymyYRAP6xyS/mz1ae9p3XEhycMHrVDxoaNPK68WGKYufWJ1n81+O9lbpAxTeCPF+L18yptmP7Aal7pchJp7NIHGhMhDnIPZrwUQs80X+EzVchLwnmjfSy4Ge/hFsKCHTxIGnehy1T2FWVHR+N+N+tpNc0idfKudqZ2sqsvmcNRMD2HUAZQRSMv7zsF4rN886wYbMuoMal+ALLWquPoM5ncmCSPmmkav52hlmcaX+ZyM5RLu1S1dnZJ8p3o0vJ2NR0pOwcQPmLAXRT3RC0noG1XPKkOYh+89TW2mVXl00FZs6vHSyq08/gxZ4h/dK1j/VA3D5rGt1W6EkvC/CncAFXygGIvERRj8e4ZH4p0YrZLASQ==
  template:
    metadata:
      name: bmc-admin-shared
      namespace: metal3
    type: Opaque
