---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bmc-admin-shared
  namespace: metal3
spec:
  encryptedData:
    password: AgB3VgnLPtUEcn8lZIEmfzoEENJnATdIVb/KTVNy1UxVlr19ObtxwQKJRnEHXy+G6BeyiyssUaYepLVGUXuAuYVRPMJYFuum/GCBnGYkm6vxvFvwyj95Hn7IiNaVJf2XWjAhBrZFtm/2nED85S4bxyn9P2X4R9cUQuyt9MyCTV/fjgTDToP3VnxY3jIFB5eRtR0PcyueE9CJfICC5AmTC4rEfoQYxkR8+4SnN2GRIWHnD4/TDM1YI7iKA0lQOLamv7uXlip5fLbjuvzDYM89qxFNpSd08Z9nWOiKqAWI/Eg+TqZijSMbbzeHgv6cZ/AOvitPLuwHQDt8YwhUwpyLYTIKtBsvp73oTBj4pGayvGTsRGJoPvBM9yVofGOP7HynoMRKXYJ/KP2pED5rDudlidaXHR63LGCOFF99YIq8c2CftC85krEoO5ausSzIt046zy50LnhOp+1KaVOQeEo9hOD9DZhFozJ+Qg1PpBJzTSYR8eOlgbhdUIeDawC0QFu722IVtSJitTyDZ1PYQUvFhkZhBw2RgODvJgiitlA5McPokDuEqr81dUnFI7aXPISF3pV5aRF7TvVl1XMjK5qEIN5KErDcERktRjihLz2hr4nZCg2kv7Rgwc80vV2MJd5zWirBteCOBknJ0Q7dd8boX/M7mjv3un2CBpgFnX9puOoeq4iKvq871kz6NAd8zHZeqDHsVFpQVQ==
    username: AgBGBIQd9gcsp0b+2c8nd4LCRkvQ0a6FwRABEPC3NSMRBB3wwfA8bcEnwqYWtHsyKsDvm2vhFPrcb4JrYq2FHtWY+3rjGaX7W8zWvQv+skvT2JGvkXPo+GcgZNeFkaEViPLoWCHeO5QtBWYYJ3iIgj/5G/Wj3qbKV/qpZvpnzYgAQNdRV94oNHPY3pcA+XPFuLX0ImAxYI63JkgHPz9GsrFgQFOG06HHhdZwAkPeQF+hl7yjTxZU14Fs7+EfOLDk37y4GzLQmuakwHDXw1HjKnjtf1jipyjc2iGAyInzO1K6RKUjBzkfV/R5aabq+o7gm3C83HBKw6LZGqVjy5l0q4hNTbQ6Uhjeb+omlzLalH4LWRrRW/8K8L2TJ6MCBUOpUM6RYJXF9akBinI4VKGFzCZD9OawBBMraU1XBiOeZfO6W3YLUcy7PvP1TxpNNFYKqSTTk3kDuxWMwYhjxbYOGhBq4SK9LgPx6QDIHkTuAq3ukMWnzqv/kEezDorVdj8gUqPgnXJV+AfPWOsUMPCvWWk8nUyT1B43z6/4MqzztRgvg8tjhxJGR5f+IIG2+AcjiUhKi/YjR53N0BfN/zcUhd/lRvD+KqFtUOd6K2u6TAdFulTNTBkoIx2CaTYY6seMRDjcPDv5w28BWH07AAXAw/L3c4PoK998HIitWH9MXxy0nX2SwwLLtelg+hjEwuLD9TV1e+GcNg==
  template:
    metadata:
      name: bmc-admin-shared
      namespace: metal3
    type: Opaque
