---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bmc-admin-shared
  namespace: metal3
spec:
  encryptedData:
    password: AgB9E7bs/zx30/iH/NRyWqI8p3OZ2IYJT0tjYW6eGUCn8pWnLDIdszuwNNB5RFPrM4iCM2Aesx0tNasMigeZDvGRP7a7ImlpYT+JJ+cKe2MY0+4OgtRyWxNA56Wcp3qfnnDW/BhaCoqYNeowY0HQP+1TrdNKmZm1bkupQsseuQ9k2xEMZT8S0AoIB4vpE6YJf1opA7E83VHvMsCDN6UuDIMHmdNXmMTdbU7VTzqMlNrIhpqN5Af4VKaCStOpn1XtgKUaoLreyVNHYVo5Lfo+NwdhorRQc90Gy38kbxajouGop9W0IzN/nAmCxrsnIhJpBFZ/LYPrxABmvLJW5YxSD/skELHaND/qwvGi6ReS+kQOzcL1xAU38UVWks8urOb6VGyS7DQMwp9GurILsguvORigOKoaukhCVmCAUc1r/dDeNGUWdIViZiy/xobjhRfeFQbY21kWw1aqsQp2aiFnplrpEb851A87Wt+8doWIQBwHwiEayhG4AJpG745WO8c8HzApxhgDdWIZ76D4c3muKbkODPvyweaq3vyCRMCPABOpZi03Rf5N2MZGRtabDcjfyjHpg6bSsQBBgF8ucL1JBcACmGOglFwUKHoxLUM8nDPeAmy0HLKkwbWCaTRpL2VNtBf9fGKwpwPDQU7yfMluIb7KPP0TltRuu1Vgb/hAByOxvyRpMEYEaVgxBhPpF59vReqmDWU+rw==
    username: AgCr70WMMeuMveJcSzQeOE2Z4F2QM8urDgaxYYeC/b/jSi8KR49lzUatptFJy9pAktiyehlpEoacbico16EkwlAAjy8JP2vC6Cmjh0ZIPF8BHPgz3Jt2XwuJclE3WQxHA3aNV57kQ76sw7uBFORFsooihgi0lBOF37oMQbDQRakuVvQxl3JMu7Q2aWgZ9kiFsGiCTqL19ljPtt+gb4FoZM1mcb8dOXlq+jSWFqvzB4A4hd0vt1pWWrLfwlpanl+j3tzZqVhBcqB/XuZMZowzKOBxxa/jLw557fRRhi6FAwtJ1AkyaFmP7ETBSvx2nQysQde8Y90HMi/40MPxiG0npvy7hRJBTsGwrTUAWRR32vh3rSdAhl+dYFrbU1NBOIWToZTIQEWre8rSin4CzbIkeQ3oJxwyS2EimNiz/OjCThkjQVpPCnPotCadCTZOgEa2nCxE6+2aPvXZFRPjnsh182h8F7WA1nRz8FTLEIjM6hjKLnvgu1JrugGrLG/aB+cUKHYvrsuBqkQ7NGM6Yf/JupV/+PMvXODUTG3Ox3IUBDvM7P2FSjiOmiNudkxG4IVyl/88JCvoctc8a0ouFpqhgka9WcH5CQYwjr0leh2Ww7BkOC4F8JL5IsMAAuf1OZ6d4ll8yv+MVSM6FOkq1JyVEKFedOvfwn4JWclYuoMKSiM+Wir2h6wBdVWv/dyLRCaB/vwBa4Bauw==
  template:
    metadata:
      name: bmc-admin-shared
      namespace: metal3
    type: Opaque
