apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: main
    path: workload-clusters/prod/core-addons/metallb
  destination:
    server: https://172.16.10.100:6443
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
