---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgB4HrvRrPy7cKfkc4Yl7Y2TVYL/fBikTtZ/JL8yatSKBm9IFZHy6hiEk9KWeArUJlBWoT+Z2DNe6ce+6phVJsLPDW1Pcx8ZFOfzZSkpIIWCacggMp2Vpv+HXLWc40Wf/VwJ1aYESloSSBAT62WA2v6kDUzGZV7euJho2kuTOdt8MjAoBWFT5678KBdXjrKRgXi1g9fMIsbfyc1T9ii5V9szEXrmo18lbcXnHkl8MNDzMJUyxqs4dd6L3FWrtguzX7zH59UgPWabHLPDo1a3NPRrVSK5mAmfrsJsBnCCa+PL4/19MGPmMroBIHf01BzXpP5DCJ1t82Ma2pAFaVAuE+Ut2Nemde/N4DeonUZRScLnig1b/XcTDGP0RZHFPuRHlBVe3Gu+piC6ObuPpqnqfO27b6l9csalgiWJYwyxCBp21oSjOZ79q/OXncXUvL5MB5Pg8b4/Hx5ya6V1UqLf4eAbNzpCvxQdI7bVw3s1nDJgf/aNKrq3tR9bfbkEDuaaubCyx1C0XLD3hwmmB3VWceM4gufu3FROA7I3TmV3HvMWljYkTSN0xBK6m4R8Sj1iSIa+t7EFA/qsQHCqHJcTGCrNDsXP9MyditHsaO2U7gnAXh4QhtMflzdoe6buUvIb89KiP9B37Pm/HAU4m8ZAWrz5VyErUhn7vt15b1Q7oHdAKJk2tiMayxZlgQnzFINHR97hNIXvxU2kO3AGxZgMPGGh9Rg6STTRMLewNe15YmNMlbyrbBZ3hmlXDCIdumqL5MUhbN6msQAQ2Lcnr/UaOBUA95Y6Q7mXOLwppbcgXCzCR1sKv7ZO14Asmlm57qVssjMH8LPm7H5Nb0mb0Vm0bcVjip2XRjM8pZ0bTe3oQ8duTHXvNDHF2l2LS0oPV3KQfjaZcbhVNhPWDSbpKIOlbZ0wWEJAx/DyHuyCSch//+JGiDLJbHFVhFTo
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare
