---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgC+07F8m28lz5qOYdGTMwLHJfB30N0Ev97s13BG+3IGW+AzvUT+0kPCXCiOEXCUPRioj+d4FmDuCgPVubYn68EOhvDofi6jog5YlX1LlMb2Yeb6wF4DGTyhTWPTNwtqryrzXz+emYCr05G7NNZKHT452gQxJbL2ttkEDS1GvC/VImjN2olZ0y8tnnwEi0y+IjZCv5IoenQYcpUgrch+r5S0+4n/1+RwVh0U+Rrv8Euf4FpEpjQNStll81t2P/JOeQt38yHaQX0Sx0UeA3yj6b1DXnOZBNeCBFOKR/A/hieyd7ncgkFng6YDDCDJZJz53nM+iGMh93qEkUzN50EFPUELLzK8wkWq7Ic+2ZYg+HR02bFSf9A7hslpJJr4i2ik1v2qXqoQ/hi2+V6S+TQZNztfOOl+g760cG4v0Zb2tPLfFbShjFC7dSt2ck4M2/rdT1WJgi3q2pePIbIK2GdgA7MVOxNiRJ3sPVwIQc/13BX5Rut72pMWv3UM2CCVcnHjdLMOtye9tv08cTZHxqVw0mS65uEF9+XNZ+HNhBp8s+QZJn5O/9HZRKxoMYpXP4ndIWF3wLiygZ0NEBzpr6KONB+RR7ipO9VoV7+h6TJIXAZnvSlNK88k7EsgBzK6i3mm0P+Gib/JS0ua6FkfXcqI81ckkpSseW5k2XgyaARsMgRnIwEDBjM/NFE0AkGEq33eZWtsI/yiv7cr+xMjHtKJ7KiOLqk6wcDGxk966cHGtH3iM6vAxoPUkqoKwdsn58qRP4axwCRWnTQLlrSWYhP7kwmY/4zy48J9mK0Lc8Il/0Yad0TDJp57sSX+CLb/w3ltePzYpogzT9TWye87pdVb7kDJBoDhWYJVfpEsSTr3kXr4pWUkyiMkz62cRuOKfSNN6Bl7QVKtYaT9+iyLwrAf+dyQIDNPGIMBqHnTokyxdbuLX9kExfNt78Kd
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare
