apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
helmCharts:
  - name: nova
    repo: https://tarballs.opendev.org/openstack/openstack-helm
    version: 2026.1.13+a659ab8a2
    releaseName: nova
    namespace: openstack
    includeCRDs: true
    valuesInline:
      manifests:
        deployment_serialproxy: false
        deployment_spiceproxy: false
        pod_rally_test: false
        job_image_repo_sync: false
      pod:
        use_fqdn:
          compute: false
      conf:
        nova:
          vnc:
            # LB IP for browser VNC console (svc.cluster.local not resolvable from browser)
            novncproxy_base_url: http://172.16.100.102:6080/vnc_lite.html
patches:
  - target:
      kind: Job
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: Sync
