apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
components:
  - ../_base
helmCharts:
  - name: ceph-adapter-rook
    repo: https://tarballs.opendev.org/openstack/openstack-helm
    version: 2026.1.3+a659ab8a2
    releaseName: ceph-adapter-rook
    namespace: openstack
    includeCRDs: true
    valuesInline:
      ceph_cluster_namespace: rook-ceph
