apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: metal3
  namespace: capi-metal3-system
spec:
  version: v1.13.1
  deployment:
    containers:
      - name: manager
        imageUrl: ghcr.io/daigo-suhara/cluster-api-provider-metal3-amd64:oci-fix
