apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - envoy-gateway.yaml
  - ingress-nginx.yaml
  - rook-ceph-operator.yaml
  - rook-ceph-cluster.yaml
  - istio.yaml
  - knative.yaml
  - kubevirt.yaml
  - kubeblocks.yaml
  - dcloud.yaml
