apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - cert-manager.yaml
  - rook-ceph-operator.yaml
  - rook-ceph-cluster.yaml
  - istio.yaml
  - knative.yaml
  - dcloud-secret.yaml
  - dcloud.yaml
