apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - coredns.yaml
  - cert-manager.yaml
  - envoy-gateway.yaml
  - cloudflared.yaml
  - rook-ceph-operator.yaml
  - rook-ceph-cluster.yaml
  - istio.yaml
  - knative.yaml
  - kubevirt.yaml
  - kubeblocks.yaml
  - dcloud-secret.yaml
  - dcloud.yaml
  - monitoring.yaml
  - gvisor.yaml
