apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keystone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm
    chart: keystone
    targetRevision: 2026.1.10+a659ab8a2
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: placement
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm
    chart: placement
    targetRevision: 2026.1.7+a659ab8a2
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm
    chart: nova
    targetRevision: 2026.1.13+a659ab8a2
    helm:
      parameters:
        - name: manifests.daemonset_compute
          value: "false"
        - name: manifests.deployment_novncproxy
          value: "false"
        - name: manifests.deployment_serialproxy
          value: "false"
        - name: manifests.deployment_spiceproxy
          value: "false"
        - name: manifests.pod_rally_test
          value: "false"
        - name: manifests.job_image_repo_sync
          value: "false"
        - name: manifests.job_cell_setup
          value: "false"
        - name: manifests.cron_job_cell_setup
          value: "false"
        - name: manifests.job_bootstrap
          value: "false"
        - name: manifests.job_storage_init
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm
    chart: glance
    targetRevision: 2026.1.11+a659ab8a2
    helm:
      parameters:
        - name: storage
          value: pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
