apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra
      chart: rabbitmq
      targetRevision: 0.1.7
      helm:
        releaseName: rabbitmq
    - repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra
      chart: mariadb
      targetRevision: 0.2.29
      helm:
        releaseName: mariadb
    - repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra
      chart: memcached
      targetRevision: 0.1.13
      helm:
        releaseName: memcached
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
