apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  sources:
    - repoURL: https://github.com/daigo-suhara/gitops-metal3.git
      targetRevision: HEAD
      path: homelab/wordpress
    - repoURL: https://charts.bitnami.com/bitnami
      chart: wordpress
      targetRevision: 27.1.5
      helm:
        releaseName: wordpress
        valuesObject:
          global:
            security:
              allowInsecureImages: true
          service:
            type: LoadBalancer
          persistence:
            size: 5Gi
          mariadb:
            enabled: false
          externalDatabase:
            host: wordpress-db.wordpress.svc.cluster.local
            port: 3306
            user: wordpress
            database: wordpress
            existingSecret: wordpress-db-password
            existingSecretPasswordKey: password
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers: [/spec/volumeClaimTemplates]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
