apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: kube-vip
  namespace: metal3
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: homelab
  releaseName: kube-vip
  repoURL: https://kube-vip.github.io/helm-charts
  chartName: kube-vip
  version: 0.6.6
  namespace: kube-system
  options:
    enableClientCache: false
    waitForJobs: true
    wait: true
    timeout: 10m0s
    install:
      createNamespace: true
    upgrade:
      maxHistory: 10
  valuesTemplate: |-
    image:
      repository: ghcr.io/kube-vip/kube-vip
      tag: v0.8.9
    config:
      address: 172.16.10.100
    env:
      vip_arp: "true"
      vip_interface: eno1
      port: "6443"
      vip_cidr: "32"
      cp_enable: "true"
      cp_namespace: kube-system
      vip_leaderelection: "true"
      vip_leasename: plndr-cp-lock
      svc_enable: "false"
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        operator: Equal
