apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: rook-ceph-cluster
  namespace: metal3
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: homelab
  repoURL: https://charts.rook.io/release
  chartName: rook-ceph-cluster
  version: 1.19.4
  namespace: rook-ceph
  releaseName: rook-ceph-cluster
  options:
    install: { createNamespace: true }
    wait: true
    timeout: 20m0s
  valuesTemplate: |-
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v19.2.3
      cleanupPolicy:
        wipeDevicesFromOtherClusters: true
      dataDirHostPath: /var/lib/rook
      mon:
        count: 3
        allowMultiplePerNode: false
      mgr:
        count: 2
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: tx1320m3-01
            devices:
              - name: sda
          - name: tx1320m3-02
            devices:
              - name: sdb
          - name: tx1320m3-03
            devices:
              - name: sdb
    cephBlockPools:
      - name: rbd
        spec:
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            imageFeatures: layering
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems: []
    cephObjectStores: []
    cephObjectStoreUsers: []
    cephFileSystemVolumeSnapshotClass:
      enabled: false
    cephBlockPoolsVolumeSnapshotClass:
      enabled: false
