apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
  namespace: metal3
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
