apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-ironic
spec:
  template:
    spec:
      containers:
        - name: ironic
          envFrom:
            - configMapRef:
                name: ironic
        - name: ironic-dnsmasq
          envFrom:
            - configMapRef:
                name: ironic
        - name: ironic-log-watch
          envFrom:
            - configMapRef:
                name: ironic
        - name: ironic-httpd
          envFrom:
            - configMapRef:
                name: ironic
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - ALL
      initContainers:
        - name: ironic-ipa-downloader
          envFrom:
            - configMapRef:
                name: ironic
