apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetal-operator-manager-role
rules:
  - apiGroups:
      - metal3.io
    resources:
      - hostclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
