apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3

resources:
  - image-pvc.yaml
  - https://github.com/metal3-io/baremetal-operator//config/default?ref=v0.13.0
  - https://github.com/metal3-io/baremetal-operator//ironic-deployment/default?ref=v0.13.0

patches:
  - path: ironic-deployment-patch.yaml
    target:
      kind: Deployment
      name: baremetal-operator-ironic
  - path: ironic-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: ironic
  - path: ironic-clusterrole-patch.yaml
    target:
      kind: ClusterRole
      name: baremetal-operator-manager-role

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: baremetal-operator-ironic
    path: ironic-volume-patch.json

replacements:
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: baremetal-operator-serving-cert
      fieldPath: .metadata.namespace
    targets:
      - select:
          kind: CustomResourceDefinition
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: /
          index: 0
          create: true
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: /
          index: 0
          create: true
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: baremetal-operator-serving-cert
      fieldPath: .metadata.name
    targets:
      - select:
          kind: CustomResourceDefinition
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: /
          index: 1
          create: true
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: /
          index: 1
          create: true
  - source:
      kind: Service
      version: v1
      name: baremetal-operator-webhook-service
      fieldPath: .metadata.name
    targets:
      - select:
          kind: Certificate
          group: cert-manager.io
          version: v1
          name: baremetal-operator-serving-cert
        fieldPaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: .
          index: 0
          create: true
  - source:
      kind: Service
      version: v1
      name: baremetal-operator-webhook-service
      fieldPath: .metadata.namespace
    targets:
      - select:
          kind: Certificate
          group: cert-manager.io
          version: v1
          name: baremetal-operator-serving-cert
        fieldPaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: .
          index: 1
          create: true
