apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3

resources:
  - ironic-support.yaml
  - https://github.com/metal3-io/baremetal-operator//config/default?ref=release-0.13.0
  - https://github.com/metal3-io/baremetal-operator//ironic-deployment/default?ref=release-0.13.0

generatorOptions:
  disableNameSuffixHash: true

patches:
  # Ironic Pod configurations
  - path: ironic-deployment.yaml
    target:
      kind: Deployment
      name: baremetal-operator-ironic
  - target:
      kind: Deployment
      name: baremetal-operator-ironic
    patch: |
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - name: ironic-data-volume
            persistentVolumeClaim:
              claimName: image-pvc

  # BMO Role enhancements
  - target:
      kind: ClusterRole
      name: baremetal-operator-manager-role
    path: bmo-privileges.yaml

  # Cert-Manager and Webhook integrations
  - target:
      kind: CustomResourceDefinition
      name: (.*).metal3.io
    path: patch-crd-annotations.yaml
  - target:
      kind: ValidatingWebhookConfiguration
      name: baremetal-operator-validating-webhook-configuration
    path: patch-webhook-configuration.yaml
  - target:
      kind: Certificate
      name: baremetal-operator-serving-cert
    path: patch-certificate-dns.yaml

configMapGenerator:
  - name: ironic
    behavior: merge
    literals:
      - PROVISIONING_INTERFACE=enx00e04c247a98
      - PROVISIONING_IP=172.16.0.10
      - PROVISIONING_GATEWAY=172.16.0.1
      - PROVISIONING_DNS=8.8.8.8
      - HTTP_PORT=6180
      - DHCP_RANGE=172.16.10.101,172.16.10.200
      - IRONIC_KERNEL_PARAMS=console=tty0 console=ttyS0,115200 nomodeset
      - IRONIC_FAST_TRACK=true
      - IRONIC_PROVISIONING_INTERFACE=enx00e04c247a98
      - DEPLOY_KERNEL_URL=file:///shared/html/images/ironic-python-agent.kernel
      - DEPLOY_RAMDISK_URL=file:///shared/html/images/ironic-python-agent.initramfs
      - IRONIC_ENDPOINT=http://172.16.0.10:6385/v1/
      - IRONIC_BASE_URL=http://172.16.0.10:6385
