apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
components:
  - ../_base
resources:
  # PreSync Job that fetches client.cinder key from Rook and creates
  # cinder-volume-rbd-keyring Secret.
  - rook-keyring-setup.yaml
helmCharts:
  - name: cinder
    repo: https://tarballs.opendev.org/openstack/openstack-helm
    version: 2026.1.14+a659ab8a2
    releaseName: cinder
    namespace: openstack
    includeCRDs: true
    valuesInline:
      manifests:
        job_image_repo_sync: false
        pod_rally_test: false
        deployment_backup: false
        job_storage_init: false
        job_backup_storage_init: false
      conf:
        cinder:
          DEFAULT:
            enabled_backends: rbd1
        backends:
          rbd1:
            rbd_pool: rbd
patches:
  - target:
      kind: Job
      name: cinder-clean
    patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: cinder-clean
