apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
helmCharts:
  - name: glance
    repo: https://tarballs.opendev.org/openstack/openstack-helm
    version: 2026.1.11+a659ab8a2
    releaseName: glance
    namespace: openstack
    includeCRDs: true
    valuesInline:
      storage: pvc
patches:
  - target:
      kind: Job
      name: glance-clean
    patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: glance-clean
  - target:
      kind: Job
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: Sync
