---
repo_url: https://github.com/daigo-suhara/homelab.git
repo_ref: main
repo_dir: /home/{{ ansible_user }}/homelab
bootstrap_kubeconfig: /home/{{ ansible_user }}/.kube/config
target_kubeconfig: /home/{{ ansible_user }}/.kube/homelab-kubeconfig

capi_version: v1.14.0
capm3_version: v1.13.2
metal3_ipam_version: v1.11.0
