apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-db
  namespace: wordpress
spec:
  rootPasswordSecretKeyRef:
    name: wordpress-db-root
    key: password
    generate: true
  username: wordpress
  passwordSecretKeyRef:
    name: wordpress-db-password
    key: password
    generate: true
  database: wordpress
  storage:
    size: 5Gi
