apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: prod-control-plane
  namespace: metal3
spec:
  template:
    spec:
      image:
        url: http://172.16.0.10:6180/images/ubuntu-2404-kube-v1.35.qcow2
        checksum: http://172.16.0.10:6180/images/ubuntu-2404-kube-v1.35.qcow2.sha256
        format: qcow2
      hostSelector:
        matchLabels:
          cluster-role: control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: prod-control-plane
  namespace: metal3
spec:
  replicas: 3
  rollout:
    strategy:
      type: RollingUpdate
  machineTemplate:
    spec:
      infrastructureRef:
        kind: Metal3MachineTemplate
        name: prod-control-plane
  kubeadmConfigSpec:
    format: cloud-config
    clusterConfiguration:
      apiServer:
        certSANs:
          - 172.16.10.100
          - 127.0.0.1
    postKubeadmCommands:
      - |
        kubectl --kubeconfig /etc/kubernetes/super-admin.conf apply -f - <<EOF
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: system:kube-apiserver-to-kubelet
        rules:
          - apiGroups: [""]
            resources: ["nodes/proxy", "nodes/stats", "nodes/log", "nodes/spec", "nodes/metrics"]
            verbs: ["*"]
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: system:kube-apiserver-to-kubelet
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:kube-apiserver-to-kubelet
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: kube-apiserver-kubelet-client
        EOF
      - |
        while [ ! -f /etc/kubernetes/super-admin.conf ]; do
          sleep 1
        done
        cp /etc/kubernetes/super-admin.conf /etc/kubernetes/kube-vip.conf
        sed -i 's/172.16.10.100/127.0.0.1/g' /etc/kubernetes/kube-vip.conf
    files:
      - content: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: kube-vip
            namespace: kube-system
          spec:
            containers:
            - args: [ "manager" ]
              env:
              - { name: vip_arp, value: "true" }
              - { name: port, value: "6443" }
              - { name: vip_interface, value: eno1 }
              - { name: vip_address, value: 172.16.10.100 }
              - { name: vip_controlplane, value: "true" }
              - { name: cp_enable, value: "true" }
              - { name: cp_namespace, value: kube-system }
              - { name: vip_leaderelection, value: "true" }
              - { name: vip_lease_duration, value: "5" }
              - { name: vip_renew_deadline, value: "3" }
              - { name: vip_retry_period, value: "1" }
              - { name: vip_kubeconfig, value: "/etc/kubernetes/kube-vip.conf" }
              image: ghcr.io/kube-vip/kube-vip:v0.8.2
              name: kube-vip
              securityContext:
                capabilities: { add: [ "NET_ADMIN", "NET_RAW", "SYS_TIME" ] }
              volumeMounts:
              - mountPath: /etc/kubernetes/kube-vip.conf
                name: kubeconfig
            hostNetwork: true
            volumes:
            - hostPath:
                path: /etc/kubernetes/kube-vip.conf
              name: kubeconfig
        path: /etc/kubernetes/manifests/kube-vip.yaml
        permissions: "0644"
  version: v1.35.4
