apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: Metal3DataTemplate
metadata:
  name: homelab-worker
  namespace: metal3
spec:
  clusterName: homelab
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: Metal3MachineTemplate
metadata:
  name: homelab-worker
  namespace: metal3
spec:
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: homelab-worker
      image:
        url: https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img
        checksum: 39abdd660255eb6f29611cce8d66229e5368ac21b8841c50a6b611ae9e6ae2dafe9db1354d185145819386bf7b6c771e28153e522c61deb95aaee7694b12f153
        checksumType: sha512
        diskFormat: qcow2
      hostSelector:
        matchLabels:
          cluster-role: worker
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: homelab-worker
  namespace: metal3
spec:
  clusterName: homelab
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: homelab
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: homelab
    spec:
      clusterName: homelab
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: homelab-worker
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
        name: homelab-worker
      version: v1.36.2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: homelab-worker
  namespace: metal3
spec:
  template:
    spec:
      format: ignition
      users:
        - name: core
          sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+3Q/eAOgoIs0pNtGvQ8ueXK1Gg8CnIdhcU9rwpeMFm suharadaigo
          sudo: ALL=(ALL) NOPASSWD:ALL
      preKubeadmCommands:
        - mkdir -p /var/lib/extensions /etc/extensions
        - curl -fsSL -o /var/lib/extensions/kubernetes.raw https://github.com/flatcar/sysext-bakery/releases/download/kubernetes-v1.36.2/kubernetes-v1.36.2-x86-64.raw
        - ln -sf /var/lib/extensions/kubernetes.raw /etc/extensions/kubernetes.raw
        - systemd-sysext refresh
        - systemctl daemon-reload
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            - name: node-labels
              value: 'node-role.kubernetes.io/worker=true'
