apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: prod-worker
  namespace: metal3
spec:
  template:
    spec:
      image:
        url: oci://ghcr.io/daigo-suhara/gitops-metal3/ubuntu:2404-v1.35.4-amd64.gz
        checksum: sha256:9e6893ec03673254f1f2deae097b20b938fe5c2c2933bfaf15038a60e6b67c22
        checksumType: ssu
      hostSelector:
        matchLabels:
          cluster-role: worker
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: prod-worker
  namespace: metal3
spec:
  clusterName: prod
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: prod
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: prod
    spec:
      clusterName: prod
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: prod-worker
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
        name: prod-worker
      version: v1.35.4
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: prod-worker
  namespace: metal3
spec:
  template:
    spec:
      format: cloud-config
