apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes
resources:
  - configmap.yaml
  - pvc.yaml
  - llama-cpp-pvc.yaml
  - llama-cpp-deployment.yaml
  - llama-cpp-service.yaml
  - deployment.yaml
  - service.yaml
  - dashboard-service.yaml
secretGenerator:
  - name: hermes-dashboard-auth
    literals:
      - username=admin
      - password=admin
