apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: github-store
spec:
  provider:
    github:
      # ここで GitHub リポジトリを指定
      repository: daigo-suhara/gitops-metal3
      auth:
        secretRef:
          # GitHub Access Token (PAT) を入れる Secret 名
          accessTokenSecretRef:
            name: github-token
            key: token
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bmc-admin-shared
  namespace: metal3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: github-store
  target:
    name: bmc-admin-shared # 最終的に作られる Secret 名
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: BMC_USERNAME # GitHub Secrets の名前
    - secretKey: password
      remoteRef:
        key: BMC_PASSWORD # GitHub Secrets の名前
