apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: capi-providers
  destination:
    server: https://kubernetes.default.svc
    namespace: capi-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
