apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: access-fixer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: system/access-fixer
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
