apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: metal3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
