apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-registration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: system/cluster-registration
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
