apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-mirror
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: system/image-mirror
  destination:
    server: https://kubernetes.default.svc
    namespace: metal3
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
    retry:
      limit: 10
      backoff: { duration: 10s, factor: 2, maxDuration: 3m }
