apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ironic.yaml
  - capi-operator.yaml
  - capi-providers.yaml
  - cert-manager.yaml
  - cluster.yaml
  - hardware.yaml
  - cluster-registration.yaml
  - cilium.yaml
