---
apiVersion: v1
kind: Node
metadata:
  name: tx1320-01
  labels:
    openstack-control-plane: enabled
    openstack-compute-node: enabled
    openvswitch: enabled
    openstack-network-node: enabled
    l3-agent: enabled
spec:
  taints: []
---
apiVersion: v1
kind: Node
metadata:
  name: tx1320-02
  labels:
    openstack-control-plane: enabled
    openstack-compute-node: enabled
    openvswitch: enabled
    openstack-network-node: enabled
    l3-agent: enabled
spec:
  taints: []
---
apiVersion: v1
kind: Node
metadata:
  name: tx1320-03
  labels:
    openstack-control-plane: enabled
    openstack-compute-node: enabled
    openvswitch: enabled
    openstack-network-node: enabled
    l3-agent: enabled
spec:
  taints: []
