apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: placement
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: homelab/openstack/charts/placement
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
