---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-mariadb-auth
  namespace: wordpress
spec:
  encryptedData:
    mariadb-password: AgBUMkf3SDInQwHofMh0XdmXW70/Ax5pd2nt+zQQQenRr/bITKkTzPYQQ2hiC/wVCxldaDcbKTq0xFi2+VtRoZkulpyCIqpA/OdAP9EzFKVKynFovgXNxnBFQ85cLPTia3VO9x/DaxUH96FrwkxDjflNopQDPDzqHt/RSk3NO6I6qu2u/pDq3RehE4i799KQfyVCZ8wqRKgMbMeUpkYFXHtMsVosd/VQOWwciA+xWNyvOFwCyEQODgNHZ2hKqjzesSI7T7fG1o3Y65L+Ehy9V4hTg1gQ/JJhaZcVakBDY9iCTY9wrvTW8872gQA4JT4SGGyrmluf/TLL64UnBHy4ZDUbwy9LhVDaHP6RihuNLIxi8xzcjzn59QMe/a0jDTKGk1SENd/PcsTCJIHASOHFpkwUO36Rfa3dLflz1jY2oMNgjtjriEHt5+qkR3XW9b5/CaBnOwim6pLpaotqR4TpL39HlU0cmxfWGBSwpXWHBeA07ZqXxuphTMreyjZtFTIILnbKjWeOI302oy4gBqL98asUmqzSbiEuiz6eqQK+6HVf0r79sDehQb+xX+aUpJmB2t76zBY2T+FC1lU/KPl6IxwD2jNYW/nq0RQsxwfOpeRnRIyZYFxFCpX7cwDw9sD9a2B/fp1IBd2yY3QUGVAL/egLVDZ2UAj02f6VCabE2baWV7TSaU00Tf2yhEIe0wTkGsweKWDsqnYd9PM5
    mariadb-root-password: AgAOklvb3PUDPMJ/R+9NBaLrLZzgnKFHh7BfXuWI8Z29RFchAMszs4DahGJdIojrEPMbk9F3khj1iaPoiHtd71KK63yAZ/c4cvfZJpX+RqQgX5Ce9lLEToKyx5/zJbdC5eqkq7kfwtbRMUzc4k4q7av4/tn7MscsDuT/PXus9pRqIJKSi2JPoXTPP/q5ODwbnGQTnZOHhOuty73N/7KGjg1+ERnS34dxHKlu5e734xAK5sfBVtUvSXyzesA7Mn4UClJSUiW/Uf36wvh5qN4Gv7RY6OqMlhKGjgD+yPkq/p7p/FKGZdRa0S+OBZ8N7/k96rz6NRcksWFTMf7mvZSxgvINqjBgDXjyifn6fV8Y62k/MJEG6zy1jB6FxKaLLmjABZ0m5jvI1HKd1lX+ootS2yPE8QxgKVi9+C8lMrM5Qh8NE2aJk1nt8pel736+fqSHvGjDDt1/zwQ2vJChEPIfgnX1ec9pYC3UIt7jPw5LWGbBsR3FCDEl8HIN9yz+okXTQH6xvnU4O9PQW4urO5PA4s9MPUwF/mnHKEnLTQv+V94V5+woP2rFAbhbzRVlnj5gnQR/N3nSyuoggS6/rFYzTOaoNnF4YR8zYB22H37idJyLYNtIOVKl2P3O79oru+8T9QQJkcMsmsBG0SbBtReSFUgYm8XyC6eJximQhCKODe1eUVHR6hxirb4ASPxMVdQ6ODyL48C00Nl28ed9
  template:
    metadata:
      name: wordpress-mariadb-auth
      namespace: wordpress
    type: Opaque
