---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-auth
  namespace: wordpress
spec:
  encryptedData:
    wordpress-password: AgByhBHNvdb/rSxvVLBVQGLgTFrkKNAV/G/bocYc6fzHbgLKxM5goigofeirAdgxUvkEkzr7putxV2DFtva8SS80lRXMY2iXejzBgqWuz82Ym6AjuYHS8FUm187feth+gSXntADAG5bHmq+ZMyah8UWM0cMWrv0zt7RcsxzGZMPt23xkrtrdW4TIOK2O27cPin2LY6zYyWa3pg0B6IaEQV5iKNgV99mEgn2REh0LzUnOZqJ8diZa+1yQj0rQ1VOvJYKBf1kDGJueo0JnJtlyo2v6NYWFsyuV4IMxnoHPRZHfon7TfByjBwWabYU/JHH4kqo3ELXe56v0lJUduRWzaQCW3AoPWbxdz5Si7yHD2WAb6zrr/J1j2+x4283d27ZJriaWL9rF3iSP0ca0JhRemitzwc146Y2tYysqhM3/VGnsWjyppPGLdaTDyjvxZ9dXcykIDsAE1OY4J8UbaJ6VnNkJBfIP/vU/Uwj94v/rU6WS767G0KNHXczXWkrH5aXf8n9t2TnHk5/YiGx5/QO2Iy/vZ/Foab8ZlpGX5qYkmT/aq7hKsGYEHRU2rfgcqsyeMwW3whmabbuQ/UVwKiBYLTlvgWvj346PVZG+fIl1U376TKN7PvIJeGDpCQ7zazocqatVz5LshuBTCCtx9BHuDIxale5uski/PlurV3EvJ0yd/uimggevkCNoFo204SQbFiNlUK+o/MWYQrAm
  template:
    metadata:
      name: wordpress-auth
      namespace: wordpress
    type: Opaque
