---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: cinder-volumes
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: glance
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: nova
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: cinder
  namespace: rook-ceph
spec:
  caps:
    mon: "profile rbd"
    osd: "profile rbd pool=cinder-volumes, profile rbd pool=nova"
    mgr: "allow rw"
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: glance
  namespace: rook-ceph
spec:
  caps:
    mon: "profile rbd"
    osd: "profile rbd pool=glance"
    mgr: "allow rw"
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: nova
  namespace: rook-ceph
spec:
  caps:
    mon: "profile rbd"
    osd: "profile rbd pool=nova, profile rbd pool=cinder-volumes"
    mgr: "allow rw"
