apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-bmo-configmap
  namespace: metal3
data:
  PROVISIONING_INTERFACE: "eth1"
  PROVISIONING_IP: "172.16.10.50"
  PROVISIONING_CIDR: "16"
  DHCP_RANGE: "172.16.10.100,172.16.10.150"
  DEPLOY_KERNEL_URL: "http://172.16.10.50:6180/images/ironic-python-agent.kernel"
  DEPLOY_RAMDISK_URL: "http://172.16.10.50:6180/images/ironic-python-agent.initramfs"
  IRONIC_ENDPOINT: "http://172.16.10.50:6385/v1/"
  IRONIC_INSPECTOR_ENDPOINT: "http://172.16.10.50:5050/v1/"
  CACHEURL: "http://172.16.10.50:6180/images"
  IRONIC_FAST_TRACK: "true"
  USE_IRONIC_INSPECTOR: "true"
  IRONIC_KERNEL_PARAMS: "console=ttyS0"
  IRONIC_BOOT_ISO_SOURCE: "http"
  HTTP_PORT: "6180"
