apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3

resources:
  - 00-namespace.yaml
  - hostclaims-crd.yaml
  - https://github.com/metal3-io/baremetal-operator//config/default?ref=release-0.9
  - https://github.com/metal3-io/baremetal-operator//ironic-deployment/default?ref=release-0.9

patches:
  - target:
      kind: Certificate
      name: baremetal-operator-serving-cert
    patch: |
      - op: replace
        path: /spec/dnsNames
        value:
          - baremetal-operator-webhook-service.metal3.svc
          - baremetal-operator-webhook-service.metal3.svc.cluster.local
  - target:
      kind: ValidatingWebhookConfiguration
      name: baremetal-operator-validating-webhook-configuration
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: baremetalhosts.metal3.io
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: hostclaims.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: bmceventsubscriptions.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: dataimages.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: hostfirmwarecomponents.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: hostfirmwaresettings.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: preprovisioningimages.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert

configMapGenerator:
  - name: ironic-bmo-configmap
    behavior: merge
    literals:
      - PROVISIONING_INTERFACE=eth1
      - PROVISIONING_IP=172.16.10.50
      - PROVISIONING_CIDR=16
      - DHCP_RANGE=172.16.10.100,172.16.10.150
      - DEPLOY_KERNEL_URL=http://172.16.10.50:6180/images/ironic-python-agent.kernel
      - DEPLOY_RAMDISK_URL=http://172.16.10.50:6180/images/ironic-python-agent.initramfs
      - IRONIC_ENDPOINT=http://172.16.10.50:6385/v1/
      - IRONIC_INSPECTOR_ENDPOINT=http://172.16.10.50:5050/v1/
      - CACHEURL=http://172.16.10.50:6180/images
      - IRONIC_FAST_TRACK=true
      - USE_IRONIC_INSPECTOR=true
      - IRONIC_KERNEL_PARAMS=console=ttyS0
      - IRONIC_BOOT_ISO_SOURCE=http
      - HTTP_PORT=6180
      - IRONIC_BASE_URL=http://172.16.10.50:6385
  - name: ironic
    behavior: merge
    literals:
      - PROVISIONING_INTERFACE=eth1
      - DHCP_RANGE=172.16.10.100,172.16.10.150
      - DEPLOY_KERNEL_URL=http://172.16.10.50:6180/images/ironic-python-agent.kernel
      - DEPLOY_RAMDISK_URL=http://172.16.10.50:6180/images/ironic-python-agent.initramfs
      - IRONIC_ENDPOINT=http://172.16.10.50:6385/v1/
      - IRONIC_BASE_URL=http://172.16.10.50:6385
      - CACHEURL=http://172.16.10.50:6180/images
      - HTTP_PORT=6180
