apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3

resources:
  - 00-namespace.yaml
  - hostclaims-crd.yaml
  - https://github.com/metal3-io/baremetal-operator//config/default?ref=release-0.9
  - https://github.com/metal3-io/baremetal-operator//ironic-deployment/default?ref=release-0.9

# ConfigMap の名前を固定し、Ironic ポッドに正しい設定を渡す
generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: CustomResourceDefinition
      name: baremetalhosts.metal3.io
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: hostclaims.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: bmceventsubscriptions.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: dataimages.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: hostfirmwarecomponents.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: hostfirmwaresettings.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert
  - target:
      kind: CustomResourceDefinition
      name: preprovisioningimages.metal3.io
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert

  - target:
      kind: ValidatingWebhookConfiguration
      name: baremetal-operator-validating-webhook-configuration
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert

  - target:
      kind: Deployment
      name: baremetal-operator-ironic
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: os-images
          hostPath:
            path: /tmp/images
            type: Directory
      - op: add
        path: /spec/template/spec/containers/3/volumeMounts/-
        value:
          name: os-images
          mountPath: /shared/html/os-images
      # ConfigMap 名を固定のものに強制置換
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: ironic
      - op: replace
        path: /spec/template/spec/containers/1/envFrom/0/configMapRef/name
        value: ironic
      - op: replace
        path: /spec/template/spec/containers/3/envFrom/0/configMapRef/name
        value: ironic

  - target:
      kind: Deployment
      name: baremetal-operator-controller-manager
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: ironic

  - target:
      kind: Certificate
      name: baremetal-operator-serving-cert
    patch: |
      - op: replace
        path: /spec/dnsNames
        value:
          - baremetal-operator-webhook-service.metal3.svc
          - baremetal-operator-webhook-service.metal3.svc.cluster.local

configMapGenerator:
  - name: ironic
    behavior: merge
    literals:
      - PROVISIONING_INTERFACE=eth1
      - PROVISIONING_IP=172.16.10.50
      - PROVISIONING_CIDR=16
      - PROVISIONING_NETMASK=255.255.0.0
      - IRONIC_REVERSE_PROXY_SETUP=false
      - DHCP_RANGE=172.16.10.100,172.16.10.200
      - IRONIC_USE_MARIADB=false
      - IRONIC_ENABLE_PBOOT=false
      - IRONIC_KERNEL_PARAMS=console=ttyS0
      - INSPECTOR_REVERSE_PROXY_SETUP=false
      - IRONIC_FAST_TRACK_TIMEOUT=0
      - IRONIC_RAMDISK_TYPE=tinyipa
      - IRONIC_INSPECTOR_VLAN_INTERFACES=all
      - IRONIC_PROVISIONING_INTERFACE=eth1
      - IPA_BASE_URL=http://172.16.10.50:6180/os-images
      - IPA_KERNEL_URL=http://172.16.10.50:6180/os-images/ironic-python-agent.kernel
      - IPA_RAMDISK_URL=http://172.16.10.50:6180/os-images/ironic-python-agent.initramfs
      - DEPLOY_KERNEL_URL=http://172.16.10.50:6180/os-images/ironic-python-agent.kernel
      - DEPLOY_RAMDISK_URL=http://172.16.10.50:6180/os-images/ironic-python-agent.initramfs
      - IRONIC_ENDPOINT=http://172.16.10.50:6385/v1/
      - IRONIC_BASE_URL=http://172.16.10.50:6385
      - CACHEURL=http://172.16.10.50:6180/os-images
      - HTTP_PORT=6180
