apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3

resources:
  - 00-namespace.yaml
  - hostclaims-crd.yaml
  - https://github.com/metal3-io/baremetal-operator//config/default?ref=release-0.9
  - https://github.com/metal3-io/baremetal-operator//ironic-deployment/default?ref=release-0.9

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: CustomResourceDefinition
      name: (.*).metal3.io
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert

  - target:
      kind: ValidatingWebhookConfiguration
      name: baremetal-operator-validating-webhook-configuration
    patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: metal3/baremetal-operator-serving-cert

  - target:
      kind: Deployment
      name: baremetal-operator-ironic
    patch: |
      - op: replace
        path: /spec/template/spec/securityContext/runAsNonRoot
        value: false
      - op: replace
        path: /spec/template/spec/initContainers/0/command
        value: ["sh", "-c", "exit 0"]
      - op: add
        path: /spec/template/spec/initContainers/-
        value:
          name: image-downloader
          image: alpine:3.20
          securityContext:
            runAsUser: 0
          command: ["sh", "-c"]
          args:
            - |
              set -ex
              apk add --no-cache curl xz jq
              DEST=/shared/html/images
              mkdir -p $DEST
              chmod -R 777 /shared/html
              # TinyIPA
              [ -f $DEST/ironic-python-agent.kernel ] || curl -L --retry 5 -o $DEST/ironic-python-agent.kernel https://tarballs.openstack.org/ironic-python-agent/tinyipa/files/tinyipa-master.vmlinuz
              [ -f $DEST/ironic-python-agent.initramfs ] || curl -L --retry 5 -o $DEST/ironic-python-agent.initramfs https://tarballs.openstack.org/ironic-python-agent/tinyipa/files/tinyipa-master.gz
              # Ubuntu 22.04 CAPI Official Image
              if [ ! -f $DEST/ubuntu-2204-kube-v1.30.0.qcow2 ]; then
                curl -L --retry 5 -o $DEST/ubuntu-2204-kube-v1.30.0.qcow2 https://syself.com/files/ubuntu-2204-kube-v1.30.0.qcow2
                curl -L --retry 5 -o $DEST/ubuntu-2204-kube-v1.30.0.qcow2.sha256 https://syself.com/files/ubuntu-2204-kube-v1.30.0.qcow2.sha256
              fi
          volumeMounts:
            - name: ironic-data-volume
              mountPath: /shared
      - op: add
        path: /spec/template/spec/containers/3/volumeMounts/-
        value:
          name: ironic-data-volume
          mountPath: /shared/html/images
          subPath: html/images
      - op: replace
        path: /spec/template/spec/containers/3/securityContext
        value:
          runAsUser: 0
      - op: replace
        path: /spec/template/spec/containers/1/livenessProbe/failureThreshold
        value: 30
      - op: replace
        path: /spec/template/spec/containers/1/readinessProbe/failureThreshold
        value: 30
      - op: replace
        path: /spec/template/spec/containers/3/livenessProbe/failureThreshold
        value: 30
      - op: replace
        path: /spec/template/spec/containers/3/readinessProbe/failureThreshold
        value: 30
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: ironic
      - op: replace
        path: /spec/template/spec/containers/1/envFrom/0/configMapRef/name
        value: ironic
      - op: replace
        path: /spec/template/spec/containers/3/envFrom/0/configMapRef/name
        value: ironic

configMapGenerator:
  - name: ironic
    behavior: merge
    literals:
      - PROVISIONING_INTERFACE=eth1
      - PROVISIONING_IP=172.16.10.50
      - PROVISIONING_GATEWAY=172.16.0.1
      - PROVISIONING_DNS=8.8.8.8
      - HTTP_PORT=6180
      - IRONIC_REVERSE_PROXY_SETUP=false
      - DHCP_RANGE=172.16.10.100,172.16.10.200
      - IRONIC_USE_MARIADB=false
      - IRONIC_ENABLE_PBOOT=false
      - IRONIC_KERNEL_PARAMS=console=ttyS0
      - INSPECTOR_REVERSE_PROXY_SETUP=false
      - IRONIC_FAST_TRACK_TIMEOUT=0
      - IRONIC_RAMDISK_TYPE=tinyipa
      - IRONIC_INSPECTOR_VLAN_INTERFACES=all
      - IRONIC_PROVISIONING_INTERFACE=eth1
      - IPA_BASE_URL=http://172.16.10.50:6180/images
      - IPA_KERNEL_URL=http://172.16.10.50:6180/images/ironic-python-agent.kernel
      - IPA_RAMDISK_URL=http://172.16.10.50:6180/images/ironic-python-agent.initramfs
      - DEPLOY_KERNEL_URL=http://172.16.10.50:6180/images/ironic-python-agent.kernel
      - DEPLOY_RAMDISK_URL=http://172.16.10.50:6180/images/ironic-python-agent.initramfs
      - IRONIC_ENDPOINT=http://172.16.10.50:6385/v1/
      - IRONIC_BASE_URL=http://172.16.10.50:6385
      - CACHEURL=http://172.16.10.50:6180/images
