apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "75"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: main
    path: clusters/prod-addons/kube-system
  destination:
    server: https://172.16.10.100:6443
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
