apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "111"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: main
    path: clusters/prod-addons/openstack
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
