apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-mariadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "120"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: mariadb
    targetRevision: master
    helm:
      releaseName: mariadb
      values: |
        labels:
          server:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          ingress:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          error_page:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          prometheus_mysql_exporter:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        pod:
          replicas:
            server: 3
          management_policy: Parallel

        volume:
          enabled: true
          class_name: ceph-rbd
          size: 10Gi

        images:
          pull_policy: "IfNotPresent"
          tags:
            mariadb: "quay.io/airshipit/mariadb:latest-ubuntu_noble"
            mariadb_perms: "quay.io/airshipit/mariadb:latest-ubuntu_noble"
            db_init: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            db_drop: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/library/docker:17.07.0"
            prometheus_mysql_exporter: "docker.io/prom/mysqld-exporter:v0.12.1"

        bootstrap:
          enabled: true

        endpoints:
          oslo_db:
            auth:
              admin:
                password: openstack-changeme
              exporter:
                password: openstack-changeme
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
