apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "125"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: rabbitmq
    targetRevision: master
    helm:
      releaseName: rabbitmq
      values: |
        labels:
          server:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          prometheus_rabbitmq_exporter:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        pod:
          replicas:
            server: 3

        volume:
          enabled: true
          class_name: ceph-rbd
          size: 5Gi

        images:
          tags:
            rabbitmq: "docker.io/library/rabbitmq:3.13-management"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/docker:17.07.0"

        endpoints:
          oslo_messaging:
            auth:
              admin:
                username: admin
                password: openstack-changeme
              openstack:
                username: openstack
                password: openstack-changeme
  destination:
    server: https://172.16.10.100:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
