apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-memcached
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "126"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm-infra.git
    path: memcached
    targetRevision: master
    helm:
      releaseName: memcached
      values: |
        labels:
          server:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        images:
          tags:
            memcached: "docker.io/library/memcached:1.6"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/docker:17.07.0"
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
