apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "127"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra/
    chart: ingress
    targetRevision: "0.2.19"
    helm:
      releaseName: ingress-openstack
      values: |
        labels:
          server:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          error_page:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        network:
          host_namespace: true

        deployment:
          mode: cluster
          type: DaemonSet

        images:
          tags:
            ingress: "registry.k8s.io/ingress-nginx/controller:v1.11.2"
            error_pages: "quay.io/airshipit/error-pages:latest-ubuntu_noble"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/docker:17.07.0"

        conf:
          ingress:
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"

        endpoints:
          ingress:
            hosts:
              default: ingress
            port:
              ingress:
                default: 80
              ingress_ssl:
                default: 443

        service:
          type: LoadBalancer
          loadBalancerIP: 172.16.10.210
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
