apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "127"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.11.2"
    helm:
      releaseName: ingress-openstack
      values: |
        controller:
          kind: DaemonSet
          hostNetwork: true
          ingressClassResource:
            name: nginx
            enabled: true
            default: false
          nodeSelector:
            openstack-control-plane: "enabled"
          image:
            registry: registry.k8s.io
            image: ingress-nginx/controller
            tag: "v1.11.2"
            digest: ""
          service:
            type: LoadBalancer
            loadBalancerIP: 172.16.10.210
          config:
            proxy-body-size: "0"
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
