apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-ovn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "128"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm-infra.git
    path: openvswitch
    targetRevision: master
    helm:
      releaseName: ovn
      values: |
        labels:
          ovn_ovsdb_nb:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          ovn_ovsdb_sb:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          ovn_northd:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          ovn_controller:
            node_selector_key: openstack-compute-node
            node_selector_value: enabled
          ovn_controller_gw:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        images:
          tags:
            ovn_ovsdb_nb: "quay.io/airshipit/ovn:latest-ubuntu_noble"
            ovn_ovsdb_sb: "quay.io/airshipit/ovn:latest-ubuntu_noble"
            ovn_northd: "quay.io/airshipit/ovn:latest-ubuntu_noble"
            ovn_controller: "quay.io/airshipit/ovn:latest-ubuntu_noble"
            ovn_controller_gw: "quay.io/airshipit/ovn:latest-ubuntu_noble"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/library/docker:17.07.0"

        volume:
          class_name: ceph-rbd

        conf:
          ovn_bridge_mappings: "external:br-ex"
          ovn_system_id_compat: false
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
