apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-libvirt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "129"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra/
    chart: libvirt
    targetRevision: "2024.2.92+628a320c"
    helm:
      releaseName: libvirt
      values: |
        labels:
          agent:
            libvirt:
              node_selector_key: openstack-compute-node
              node_selector_value: enabled

        conf:
          ceph:
            enabled: true
          qemu:
            user: "root"
            group: "root"
          libvirt:
            listen_addr: "0.0.0.0"

        images:
          tags:
            libvirt: "quay.io/airshipit/libvirt:ubuntu_noble"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/library/docker:17.07.0"
            libvirt_exporter: "docker.io/prom/libvirt-exporter:v0.1.0"

        network:
          backend:
            - ovs
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
