apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "131"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: glance
    targetRevision: master
    helm:
      releaseName: glance
      values: |
        labels:
          api:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          job:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          registry:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        images:
          tags:
            bootstrap: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            db_init: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            glance_db_sync: "quay.io/airshipit/glance:latest-ubuntu_noble"
            db_drop: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            ks_endpoints: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            ks_service: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            ks_user: "quay.io/airshipit/openstack-client:latest-ubuntu_noble"
            rabbit_init: "docker.io/library/rabbitmq:3.13-management"
            glance_api: "quay.io/airshipit/glance:latest-ubuntu_noble"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/library/docker:17.07.0"

        manifests:
          test: false

        storage: pvc
        volume:
          class_name: ceph-rbd
          size: 10Gi

        conf:
          ceph:
            enabled: true
          glance:
            DEFAULT:
              log_config_append: null
              show_image_direct_url: true
            glance_store:
              default_store: rbd
              rbd_store_pool: glance
              rbd_store_user: glance
              rbd_store_ceph_conf: /etc/ceph/ceph.conf

        endpoints:
          identity:
            auth:
              admin:
                password: openstack-changeme
              glance:
                password: openstack-changeme
          oslo_db:
            auth:
              admin:
                password: openstack-changeme
              glance:
                password: openstack-changeme
          oslo_messaging:
            auth:
              admin:
                username: admin
                password: openstack-changeme
              glance:
                username: glance
                password: openstack-changeme
          image:
            hosts:
              default: glance-api
          ceph_object_store:
            auth:
              glance:
                secret: glance-ceph-client-key
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
