apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-cinder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "133"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm/
    chart: cinder
    targetRevision: "2025.2.27+c2adf0f13"
    helm:
      releaseName: cinder
      values: |
        labels:
          api:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          backup:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          scheduler:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          volume:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled
          job:
            node_selector_key: openstack-control-plane
            node_selector_value: enabled

        images:
          tags:
            bootstrap: "quay.io/airshipit/openstack-client:2025.1-ubuntu_noble"
            db_init: "quay.io/airshipit/openstack-client:2025.1-ubuntu_noble"
            cinder_db_sync: "quay.io/airshipit/cinder:2025.1-ubuntu_noble"
            db_drop: "quay.io/airshipit/openstack-client:2025.1-ubuntu_noble"
            ks_endpoints: "quay.io/airshipit/openstack-client:2025.1-ubuntu_noble"
            ks_service: "quay.io/airshipit/openstack-client:2025.1-ubuntu_noble"
            ks_user: "quay.io/airshipit/openstack-client:2025.1-ubuntu_noble"
            rabbit_init: "docker.io/library/rabbitmq:3.13-management"
            cinder_api: "quay.io/airshipit/cinder:2025.1-ubuntu_noble"
            cinder_backup: "quay.io/airshipit/cinder:2025.1-ubuntu_noble"
            cinder_scheduler: "quay.io/airshipit/cinder:2025.1-ubuntu_noble"
            cinder_volume: "quay.io/airshipit/cinder:2025.1-ubuntu_noble"
            cinder_volume_usage_audit: "quay.io/airshipit/cinder:2025.1-ubuntu_noble"
            dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble"
            image_repo_sync: "docker.io/docker:17.07.0"

        manifests:
          test: false

        conf:
          cinder:
            DEFAULT:
              log_config_append: null
              enabled_backends: ceph
              default_volume_type: ceph
            ceph:
              volume_driver: cinder.volume.drivers.rbd.RBDDriver
              rbd_cluster_name: ceph
              rbd_pool: cinder-volumes
              rbd_ceph_conf: /etc/ceph/ceph.conf
              rbd_flatten_volume_from_snapshot: false
              rbd_max_clone_depth: 5
              rbd_store_chunk_size: 4
              rados_connect_timeout: -1
              rbd_user: cinder
              rbd_secret_uuid: 457eb676-33da-42ec-9a8c-9293d545c337

        endpoints:
          identity:
            auth:
              admin:
                password: openstack-changeme
              cinder:
                password: openstack-changeme
          oslo_db:
            auth:
              admin:
                password: openstack-changeme
              cinder:
                password: openstack-changeme
          oslo_messaging:
            auth:
              admin:
                username: admin
                password: openstack-changeme
              cinder:
                username: cinder
                password: openstack-changeme
          volume:
            hosts:
              default: cinder-api
          ceph_block_storage:
            auth:
              cinder:
                secret: cinder-ceph-client-key
  destination:
    server: https://172.16.10.10:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
