apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/gitops-metal3.git
    targetRevision: HEAD
    path: system/apps/external-secrets-config/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
