apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: BackupRepo
metadata:
  name: dcloud-default
  annotations:
    dataprotection.kubeblocks.io/is-default-repo: "true"
spec:
  storageProviderRef: pvc
  accessMethod: Mount
  pvReclaimPolicy: Retain
  volumeCapacity: 200Gi
  config:
    storageClassName: general
